export const allLanguages = [
  { name: "العربية", code: "ar" },
  { name: "العامية المصرية", code: "arz" },
  { name: "الإنجليزية", code: "en" },
  { name: "الفرنسية", code: "fr" },
  { name: "الإسبانية", code: "es" },
  { name: "الألمانية", code: "de" },
  { name: "الصينية", code: "zh" },
  { name: "اليابانية", code: "ja" },
  { name: "الكورية", code: "ko" },
  { name: "الروسية", code: "ru" },
  { name: "الهندية", code: "hi" },
  { name: "البرتغالية", code: "pt" },
  { name: "الإيطالية", code: "it" },
  { name: "الهولندية", code: "nl" },
  { name: "السويدية", code: "sv" },
  { name: "التركية", code: "tr" },
  { name: "البولندية", code: "pl" },
  { name: "اليونانية", code: "el" },
  { name: "العبرية", code: "he" },
  { name: "التايلاندية", code: "th" },
  { name: "الفيتنامية", code: "vi" },
  { name: "البنغالية", code: "bn" },
  { name: "الدانماركية", code: "da" },
  { name: "الفارسية", code: "fa" },
  { name: "الفنلندية", code: "fi" },
  { name: "الكانادية", code: "kn" },
  { name: "اللاتينية", code: "la" },
  { name: "الليتوانية", code: "lt" },
  { name: "المالايالامية", code: "ml" },
  { name: "النرويجية", code: "no" },
  { name: "الفرسية", code: "ps" },
  { name: "الرومانية", code: "ro" },
  { name: "الصربية", code: "sr" },
  { name: "التاميلية", code: "ta" },
  { name: "التشيكية", code: "cs" },
  { name: "الأوكرانية", code: "uk" },
  { name: "الأردية", code: "ur" },
  { name: "الويلزية", code: "cy" },
  { name: "الأرمينية", code: "hy" },
  { name: "البلغارية", code: "bg" },
  { name: "الكتالونية", code: "ca" },
  { name: "الكرواتية", code: "hr" },
  { name: "الإستونية", code: "et" },
  { name: "الغجرية", code: "hu" },
  { name: "الكمبودية", code: "km" },
  { name: "اللغة الأمازيغية", code: "ber" },
  { name: "البوسنية", code: "bs" },
  { name: "الكانتونية", code: "yue" },
  { name: "الكورنيش", code: "kw" },
  { name: "الكردية", code: "ku" },
];

export const contentStyles = [
  { name: "رسمي", value: "Formal" },
  { name: "واقعي", value: "Realistic" },
  { name: "متفائل", value: "Optmistic" },
  { name: "إحترافي", value: "Professional" },
  { name: "ساخر", value: "Sarcastic" },
  { name: "سعيد", value: "Happy" },
  { name: "متحمس", value: "Excited" },
  { name: "حزين", value: "Wistful" },
  { name: "جاف", value: "Stark" },
  { name: "نصيحة", value: "Advisory" },
  { name: "إحائي", value: "Suggestive" },
  { name: "نادم", value: "Regretful" },
  { name: "مرح", value: "Funny" },
  { name: "متشائم", value: "Pessimistic" },
  { name: "ودود", value: "Friendly" },
];
