import icon_main from "../../assets/Images/contentsectionicon/main.svg"
export const ALL_CATEGORIES = {
  id: "0d5b9310-a672-42de-9564-94a813fe18b6",
  name: "جميع النماذج",
  slug: "all",
  cat_icon:icon_main,
  is_active: true,
};

export const ALL_LANGUAGES = [
  { name: "العربية", value: "ar" },
  { name: "العامية المصرية", value: "العامية المصرية" },
  { name: "الإنجليزية", value: "en" },
  { name: "الفرنسية", value: "fr" },
  { name: "الإسبانية", value: "es" },
  { name: "الألمانية", value: "de" },
  { name: "الصينية", value: "zh" },
  { name: "اليابانية", value: "ja" },
  { name: "الكورية", value: "ko" },
  { name: "الروسية", value: "ru" },
  { name: "الهندية", value: "hi" },
  { name: "البرتغالية", value: "pt" },
  { name: "الإيطالية", value: "it" },
  { name: "الهولندية", value: "nl" },
  { name: "السويدية", value: "sv" },
  { name: "التركية", value: "tr" },
  { name: "البولندية", value: "pl" },
  { name: "اليونانية", value: "el" },
  { name: "العبرية", value: "he" },
  { name: "التايلاندية", value: "th" },
  { name: "الفيتنامية", value: "vi" },
  { name: "البنغالية", value: "bn" },
  { name: "الدانماركية", value: "da" },
  { name: "الفارسية", value: "fa" },
  { name: "الفنلندية", value: "fi" },
  { name: "الكانادية", value: "kn" },
  { name: "اللاتينية", value: "la" },
  { name: "الليتوانية", value: "lt" },
  { name: "المالايالامية", value: "ml" },
  { name: "النرويجية", value: "no" },
  { name: "الفرسية", value: "ps" },
  { name: "الرومانية", value: "ro" },
  { name: "الصربية", value: "sr" },
  { name: "التاميلية", value: "ta" },
  { name: "التشيكية", value: "cs" },
  { name: "الأوكرانية", value: "uk" },
  { name: "الأردية", value: "ur" },
  { name: "الويلزية", value: "cy" },
  { name: "الأرمينية", value: "hy" },
  { name: "البلغارية", value: "bg" },
  { name: "الكتالونية", value: "ca" },
  { name: "الكرواتية", value: "hr" },
  { name: "الإستونية", value: "et" },
  { name: "الغجرية", value: "hu" },
  { name: "الكمبودية", value: "km" },
  { name: "اللغة الأمازيغية", value: "ber" },
  { name: "البوسنية", value: "bs" },
  { name: "الكانتونية", value: "yue" },
  { name: "الكورنيش", value: "kw" },
  { name: "الكردية", value: "ku" },
];

export const CONTENT_STYLES = [
  { name: "رسمي", value: "Formal" },
  { name: "واقعي", value: "Realistic" },
  { name: "متفائل", value: "Optmistic" },
  { name: "إحترافي", value: "Professional" },
  { name: "ساخر", value: "Sarcastic" },
  { name: "سعيد", value: "Happy" },
  { name: "متحمس", value: "Excited" },
  { name: "حزين", value: "Wistful" },
  { name: "جاف", value: "Stark" },
  { name: "نصيحة", value: "Advisory" },
  { name: "إحائي", value: "Suggestive" },
  { name: "نادم", value: "Regretful" },
  { name: "مرح", value: "Funny" },
  { name: "متشائم", value: "Pessimistic" },
  { name: "ودود", value: "Friendly" },
];

export const RESULT_NUM = Array(3)
  .fill(0)
  .map((item, index) => ({ name: index + 2, value: index + 2 }));
